language: go
go:
  - 1.11

go_import_path: github.com/samuel/go-zookeeper

jdk:
  - oraclejdk9

sudo: false

branches:
  only:
    - master
    - dev

before_install:
  - make travis ZK_VERSION=${zk_version}

before_script:
  - go vet ./...
  - go fmt ./...

script:
  - jdk_switcher use oraclejdk9
  - go build ./...
  - make test

env:
  global:
    secure: Coha3DDcXmsekrHCZlKvRAc+pMBaQU1QS/3++3YCCUXVDBWgVsC1ZIc9df4RLdZ/ncGd86eoRq/S+zyn1XbnqK5+ePqwJoUnJ59BE8ZyHLWI9ajVn3fND1MTduu/ksGsS79+IYbdVI5wgjSgjD3Ktp6Y5uPl+BPosjYBGdNcHS4=
  matrix:
    - zk_version=3.5.4-beta
    - zk_version=3.4.12
