language: go
go:
  - 1.10
go_import_path: github.com/samuel/go-zookeeper/zk

jdk:
  - oraclejdk9

sudo: false

branches:
  only:
    - master
    - dev

before_install:
  - make travis ZK_VERSION=${zk_version}

before_script:
  - go vet ./...
  - go fmt ./...

script:
  - jdk_switcher use oraclejdk9
  - go build ./...
  - go test -i -race ./...
  - go test -race -covermode atomic -coverprofile=profile.cov ./zk
    #  - goveralls -coverprofile=profile.cov -service=travis-ci

env:
  matrix:
    - zk_version=3.5.4-beta
    - zk_version=3.4.12
